// <auto-generated />
namespace AFJ.Empregos.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DefaultConnectionv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DefaultConnectionv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010180018545_DefaultConnection-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
